### ISSUE TITLE
BranchPoint is not JSON serializable

### ISSUE THREAD

**Issue by neitzke** [chan-y-park/loom#21]
Just now I tried a few times to save generated spectral networks; each time I got an error like:

```
TypeError: <loom.trivialization.BranchPoint instance at 0x7f3f9d634128> is not JSON serializable
```

**Comment by chan-y-park** [comment]
Fixed the problem. Note to everyone including myself: every attribute of `SWall` and `Joint` should be something that can be directly cast into text to be saved as JSON data. For example, this issue occurred because an instance of `BranchPoint` was a part of `SWall.cuts_intersections`.

**Comment by neitzke** [comment]
Thanks, Chan, that will be a big help!

**Comment by chan-y-park** [comment]
Reopening this regarding issue #28

**Comment by plonghi** [comment]
Chan, are already at work on this? Otherwise I could take care of it quickly

**Comment by chan-y-park** [comment]
Feel free to work on it — I was not specifically pursuing the issue but was hoping to correct it while I am continuing the work of implementing the web UI and merging the current master into it.

**Comment by plonghi** [comment]
Should work now.
