### ISSUE TITLE
Saving trivialization data

### ISSUE THREAD

**Issue by chan-y-park** [chan-y-park/loom#26]
Currently the trivialization data of a spectral network is not saved in the data file, but generated when loading a data file. This requires unnecessary repetition of the same analysis and will be a bottleneck when trying to load a given data using a web UI. On the other hand, saving and loading a trivialization data requires a careful refactoring of SWDataWithTrivialization.

**Comment by plonghi** [comment]
When I save data, I actually just use 'pickle' to save the configuration data and the results of the analysis,
it's basically two lines of code to save data, and two lines to load data.
Everything seems to be working fine with that, but more importantly,  there's no interference with how we write the code. 
Perhaps we already went over this, but is there any reason for not using pickle?

**Comment by chan-y-park** [comment]
For a short-term use like testing or debugging, using `pickle` is fine. But for a long-term purpose I prefer `JSON` for the following reasons.
- `pickle` is not cross-platform compatible, i.e. a data saved from a Mac may not be loaded on a Linux. Sometimes it's even version-specific. So a pickled data saved by one machine is not expected to be understandable from other machines.
- `JSON` is a well-standardized form of saving data, so there are many libraries that can understand such a data format.
- `JSON` forces us to carefully think about what and how to save and load data.
- `JSON` is known to perform at least the same as and usually better than `pickle`.
- Last but not least, it's usually better to save any piece of data in a text file rather than in a binary file, because a text data can be understood by anyone and by any program. Suppose we generated a golden piece of data (ha!), and revisited the data after a long time. Usually it's much easier to retrieve the information when it's a text data. If the size of the text file is too big, we can just compress it in a well-known format like `zip`.

**Comment by plonghi** [comment]
A memo regarding this: having just re-fixed the serialization of branch point I came to grasp the issue a bit better. I find that being able to have attributes of a class involve other classes is quite important. 
In the example of SWall.cuts_intersections, instead of having objects of type BranchPoint inside, we are forced to introduce extra conventions, such as labels, so that we store the label in the attribute. Then, based on the convention we retrieve the object by using its label.
This is not a minor change in the way we have to code, and quite a constraint with respect to the power of the language of python.
I am actually a bit worried about refactoring SWDataWithTrivialization to comply with this, not just because it involves complications but because it may force us to follow a slightly twisted logic, likely hindering readability of the code.
Although this doesn't seem urgent, I would like to have a thorough discussion about this, before anyone modifies the class for this purpose.

**Comment by chan-y-park** [comment]
I am planning to work on saving the trivialization data in JSON as soon as I'm done with building a prototype of web UI. Indeed it requires a semi-major overhaul in `SWDataWithTrivialization`, but I think there is no way around it. For example, in order to transfer data to the web UI part, pickling the data is not a good way to do it, because on the web client part almost everything is done in Javascript.

I agree with you that in the main part of the program it's awkward to refer objects by labels. So that's why we need a careful separation between dynamically loaded data, which will include Python objects, and statically saved data, which will contain text (i.e. JSON format) data only.

Because implementing web UI requires reconsideration of every corner of `loom` framework, let me visit this issue after I'm done with that so that I won't make a mistake of implementing something prematurely, so please bear with me for a while. ;) But please feel free to post your opinion/idea/etc on this thread so that we can have a good basis to start working on this issue.

**Comment by plonghi** [comment]
Here's a simple workaround, that I would prefer by far.
Since the issue is only plotting and saving data, why don't we build a new class, say StoredSWData, which stores the information of SWDataWithTrivialization (or at least, the relevant part of it) in a way that is JSON-serializable. 
Of course, it would be a different class from the full SWDataWithTrivialization (<strike>presumably a daughter class</strike> similar to a daughter, but not quite the same), but I think it would be enough for the purpose.
In this way we may both retain flexibility in coding, and solve the bottleneck problem, with a minimal effort in writing new code.

**Comment by chan-y-park** [comment]
Well, building a separate class won't be necessarily helpful if we want to rebuild an instance of SWDataWithTrivialization from the saved data. 

If we just want to save data to plot of course it's a different matter, but I want to have a functionality to fully restore the data, because then we can 'extend' previously saved data, if needed.

I think there may not be much work to be done, in fact. I just want to take some time to carefully assess the situation. For example, we were able to save SpectralNetwork without any separate class to save data, and it just required simple load & save functions for its attributes.

**Comment by plonghi** [comment]
I'm a bit lost, I don't see a precise goal here.
Above, you said the main concern was to be able to have all the network and trivialization data available via JSON, which I agree is reasonable. As you said, just building a suitable class for that purpose works just fine.

**Comment by chan-y-park** [comment]
The reason we save data is to load them onto `loom` so that we can get back to the exact state where we saved the data. That is, we need to load two objects, `SWDataWithTrivialization` and `SpectralNetwork` onto the memory as Python objects.

In order to do that, we need to be able to construct those objects from JSON data. That is being done for `SpectralNetwork` now, but not for `SWDataWithTrivialization`, which is currently being constructed from the configuration every time when we load a saved data. The goal is enabling constructing `SWDataWithTrivialization` from the JSON data.

Now, we want `SWDataWithTrivialization` to have Python objects as its attribute. But this cannot be done in the JSON format, because it's just a text file. Instead, when we load the JSON data, we need to instantiate Python objects as attributes of `SWDataWithTrivialization` using the JSON data. That's why some careful consideration is needed and also having a separate class saving the JSON data doesn't help in this procedure. On the other hand, this is what is being done for `SpectralNetwork`, so it's not a big deal, I just want to review `SWDataWithTrivialization` to make any commitment for the format of the data.

**Comment by plonghi** [comment]
Well, I understand exactly how loom works, and I understand exactly what the problem with JSON is.
I also understand what you would like to do to solve the problem.

What I'm questioning is whether we really have to compromise the way we code, giving up a powerful principle of objective programming, such as having objects as attributes.
I'm really asking why can't we be happy with having all the data contained in some other format, such as a class built for this purpose, it would still be formatted to be saved via JSON, then loaded and analyzed. 

I'm also saying that going down that road will affect pervasively and permanently the way we will have to code, and it's a decision that should be evaluated carefully, and together. 
Unfortunately, that was not the case for the introduction of JSON, its sudden appearance without explanation led to inconsistencies, like issue #21. 

In addition to the solution I already proposed, let me add more possibilities.
1) There are ways to automatically JSON-serialize classes, see for example the answer of Onur Yildirim (not the 1st, but the 2nd answer) on this <a href = "http://stackoverflow.com/questions/3768895/python-how-to-make-a-class-json-serializable">thread</a>. His proposal is a powered-up version of mine, essentially.
2) There is a library called <a href = "http://jsonpickle.github.io">Jsonpickle</a>, which claims to handle complex cases, such as ours. I haven't checked whether it's multi-platform and how well it works, though.
3) Along the lines of what I already proposed: we could write JSON-compatible 'storage' classes from scratch for the sole purpose of storing the data. The first advantage is that these classes could be completely data-analysis-oriented, for example we could endow them with their own methods to analyze the data stored in their attributes. Another advantage is that a user studying the data through a 'storage' class would then have a very clean interface, free of the clutter that comes with our internal classes and all their attributes and methods. Yet another bonus, is that we can always write methods for a 'storage' class that re-creates our richer 'core' classes from the data it contains.

I find option 3 the cleanest, the most flexible, and the least interfering with the workings of loom's core. 
It certainly requires a bit of work, but in my view this feature is not urgent either, what we have will be fine for some time.
There are certainly plenty more possibilities to consider, we shouldn't rush for something that constrains us so much.

**Comment by chan-y-park** [comment]
Oh, no. I'm not saying we should change the way we code. I'm saying that we need to add some methods to the current `SWDataWithTrivialization` so that JSON data can be saved and loaded. Again that's how we do it for `SpectralNetwork`. I have no plan to compromise the current design of the class.

And also I'm not against the idea of the storage class itself, what I am saying is we need to figure out how to build an instance of `SWDataWithTrivialization` from the saved data, whatever format it has.

**Comment by plonghi** [comment]
Great, thanks, I guess we are both back on the same page then! 
Let's give it some further thought once we have concrete proposals, whoever picks this up.

**Comment by chan-y-park** [comment]
Saving trivialization implemented.
