### ISSUE TITLE
Too many intersections reported

### ISSUE THREAD

**Issue by chan-y-park** [chan-y-park/loom#33]
When running the configuration `D_4_AD_from_A_2.ini`, there are many occasions that hundreds of intersections are found between two S-walls, which doesn't sound right. More investigation required.

**Comment by chan-y-park** [comment]
Turned out that this is related to the issue #3. The problem here was that `loom` tries to calculate intersections between the two S-walls, one being the incoming S-wall of a 3-way junction and another being the outgoing S-wall of the same charge. See the `plot_index = 11` of
http://chan.physics.rutgers.edu/loom/plot?data=D_4_AD_from_A_2
(it takes a few moment to load the data)
especially around the region [[-1.5, -1], [0, 0.5]] where we have S-walls #20 and #23, which are the culprits.

**Comment by chan-y-park** [comment]
Currently we find intersections between two S-walls. Because we now have the trivialization, by changing this to finding intersections between segments of S-walls, where each segment is labelled by a root, and then first check the root types before actually calculating intersections, will prevent the issue of finding too many intersections. But treating 3-way junctions is a separate and important issue.

**Comment by plonghi** [comment]
Checking the 'compatibility' of two segments before looking for their intersection is a pretty important feature to implement, it will save a lot of time as the number of walls grows.
Besides the issue with 6-way joints, there will be many nearby incompatible walls also when we are close to a K-wall phase, or more simply in chambers with wild BPS states. So it would really help to implement such a check before looking for intersections, quite generally.

**Comment by chan-y-park** [comment]
The reason that `loom` does not check the compatibility is because the current joint-finding algorithm was implemented before we had the trivialization. Now we have a trivialization implemented checking the compatibility is within reach, I will go ahead to implement it.

**Comment by chan-y-park** [comment]
fixed in fa21f38b231716b2445be942d8c87f8d5da40cb9, but actually the performance got slightly worse, about 5%, because of the additional checks.
