### ISSUE TITLE
No log output in terminal

### ISSUE THREAD

**Issue by plonghi** [chan-y-park/loom#34]
Loom is not displaying logging output in the terminal anymore.
It is quite important for development and debugging, should restore asap.

**Comment by chan-y-park** [comment]
Currently logging output to a terminal (`stdout`) is disabled by default. Please use one of the following methods to check logs.
- `loom` will generate a log file in `loom/logs`. To display the log file to a terminal, use for example `tail -f log_file_path`.
- After importing `loom`, run the following to print the logging messages to a terminal.

```
>>> import logging, sys
>>> loom.set_logging(logger_name='loom', logging_level=logging.INFO, 
... logging_stream=sys.stdout, remove_handlers=False)
```

**Comment by plonghi** [comment]
Why can't we have stdout enabled?

**Comment by chan-y-park** [comment]
Well, there are many reasons, and if I list just a few of them that hits my brain,
- It messes up web server log for web UI
- It makes it complicated to deal with GUI logs
- It duplicates the same log when running `loom` on IPython (Jupyter) notebook.
- One can redirect logs to `stdout` anytime using the command I posted above.

But it seems that we have a need to restore the stdout logging when running on a terminal by default, so I will try to find a way to make everyone happy. But it will take a while...

**Comment by chan-y-park** [comment]
Note to myself: add a timestamp to a `loom` log file, as is done for `web_loom` log files.

**Comment by plonghi** [comment]
I see, these are all valid reasons.
On the other hand, I still think for the version on Github the priority should be development, and it would be desirable to keep the terminal output.
But in the meantime, I'm fine with disabling it again by defalut, I will just introduce an method for enabling it after loading loom.

**Comment by chan-y-park** [comment]
Well, the issue with the version priority is, as you can remember from our previous discussion the master branch is supposed to be for the het-math2 that runs the main web UI and is not supposed to be a developmental version, because it cannot be updated as frequently as we want. Anyway, I will try to come up with make it work with terminal too soon.

By the way, why do you want to introduce such a method? Doesn't `loom.set_logging` work for you? If that's the case, please let me know more about it so that I can fix it.

**Comment by plonghi** [comment]
You are right, that should work too. So let's stick with it.
Regarding compatibility of web-UI, we could make a branch dedicated to the version that runs on het-math2, and keep master for development.
