### ISSUE TITLE
duplicate data structures?

### ISSUE THREAD

**Issue by plonghi** [chan-y-park/loom#35]
Minor bug, but saved data exhibits all these types of attributes for sw_data

sw_data.irregular_punctures  
sw_data.irregular_singulrarities
sw_data.irregular_singularities 

clearly they are duplicates, should hunt down the source of inconsistency, not urgent.

**Comment by plonghi** [comment]
Fixed these minors in latest push to master branch. (also introduced a small patch in the plotting module, in lines 73-87, which at some point should be resolved in a better way.)

But I came across an important related bug. 
When studying pure SYM, such as pure SO(6), the branch cut from irregular singuarity at z=0 is ignored.
Saved results show that this used to work fine up to mid-october, so the issue must be in a recent revision.

**Comment by plonghi** [comment]
Localized the issue in how data is saved via json.
Part of the data gets corrupted when saved, in particular the attribute SWall.cuts_intersections loses all intersections due to irregular punctures when the data is saved by json.
This results in S-walls which don't change root type at cuts with irregular singularities, when plotting from a saved data file.

**Comment by chan-y-park** [comment]
I think I fixed the same or a similar problem in previous commits, see if the following is helpful.
https://github.com/chan-y-park/loom/commit/7eaeb05e0150f830fae1c29e397330d385fb640c
https://github.com/chan-y-park/loom/commit/9a4fd307b35c594fe9b1347c05f0b0ebe41d4f4c
and there was another minor issue regarding saving `rp.i`, see
https://github.com/chan-y-park/loom/commit/abed7239a1c344d7e679d754b1f6ff965bd5ea95

All these commits are probably lost during the rollback of the master.
