### ISSUE TITLE
Joint rule

### ISSUE THREAD

**Issue by chan-y-park** [chan-y-park/loom#7]
The root-type of descendant S-walls is now obtained directly via the trivialization module, by comparing the x-data of the wall with the sheet-weight dictionary. But it would be more coherent to just define the root to be the sum of the roots of the parent S-walls.
Likewise, the initial sheets (which are used in the ODE for evolution) should be obtained by using the data of all weight_pairs corresponding to that new root (there's a function giving such pairs), and then using the sheet-weight dictionary.

Alternatively, a much cheaper alternative, would be to leave things as they are. But introducing a check that the initial root-type of the descendant really is the sum of the two root-types of its parents.

One thing that we have to keep in mind is that the joint rule is yet our conjecture. So it may be necessary that we have the functionality of generating joint candidates by just concatenation of S-walls and then check against our conjecture. Probably we may need to separate algorithms to find joints, one using concatenation and the other using root algebra.

We should then update the current algorithm to do something similar to what it’s already doing, but it probably needs a small update because the structure of an S-wall’s sheets should have changed by now, and some joints may be missing.

More precisely, we need to enhance the set of sheets carried by an S-wall (which is not taken care of  yet, only the splittings and the corresponding set of weight-pairs along each section of the S-wall implemented currently).

**Comment by plonghi** [comment]
With the current algorithm for joint creation, if walls S_alpha and S_beta meet, and 
-alpha is orthogonal to beta,
-(ij) \in P_alpha and (jk) \in P_beta
There will be a joint between the walls that gives rise to a third wall, right?
(Our theory construction would forbid such a joint instead)

If we know this is correct, why use the current joint algorithm to check our conjecture? already 
Isn't this already a difference between the two?

**Comment by chan-y-park** [comment]
Indeed it is, and we see one example of such a joint when we consider `D_3`. In that case we have to exclude such a joint to get a 2d BPS spectrum that is consistent with a coset model. We will test the 4d BPS spectra of `G = SO(6)` and compare the result with the BPS quiver analysis result.

Another interesting check will be studying the 2nd fundamental representation of `A_3`, whose weight structure is the same as the 1st fundamental representation of `D_3`. Here we can investigate 2d and 4d BPS spectra and compare the result with those from the 1st fundamental rep cover of `A_3`. This is a good test of our conjectures in many ways. We're heading there.

**Comment by plonghi** [comment]
Well, I'm really asking whether it's even worth proceeding with the current joint rule, if we already know it's giving wrong results (spectra that are incompatible with the deformations of coset models).

While it's true that we need to do checks, as you pointed out, there are other ways to make those.
So, I'm wondering if we should proceed right away implementing the joint rule of our note (the 'Lie-algebraic' rule).

**Comment by chan-y-park** [comment]
Ah, I see your point. You're right, I just wanted to have, at the back of my mind, that if the Lie-algebraic rule somehow does not work, then we should consider going back to path concatenation. But definitely we should proceed with our currently conjectured rule for now and see if it gives us consistent results.

**Comment by plonghi** [comment]
One more thing. Currently, one of the attributes of S-walls is 'x', which is a list of sheet-coordinates. But, S-walls are really trajectories on C, hence the attribute 'z' already contains their basic geometric info. Moreover, to keep track of which sheets they run on, we already have other ways: the attribute 'local_weight_pairs', for example.
If we want to know the 'x' sheets at a given z, we could simply write a method which gives such x's, instead of keeping such info along the whole wall. 
In fact such info seems redundant, especially if we switch to the 'Lie-algebraic rule' for joint formation. Right now we aren't using the x's data anywhere, and again, if we need it at a given point, we can simply generate it via a method of the class.
This way we should save quite some space when saving data files, especially with higher-reps.
